export {
  EntityType,
  ENTITY_TYPES,
  TYPE_PREFIXES,
  STATUSES,
  type Status,
  type Reference,
  type Entity,
  isValidEntityId,
  parseEntityId,
  parseEntityNum,
  formatEntityId,
  nextEntityId,
  getTypeFromId,
} from './entity-types.js';

export {
  SUBSTRATES,
  EntitySchema,
  getSubstrate,
  BaseEntitySchema,
  StatusSchema,
  ReferenceSchema,
  TaskSchema,
  EpicSchema,
  FolderSchema,
  ArtifactSchema,
  MilestoneSchema,
  CronSchema,
  MemorySchema,
  RuntimeSubstrateDefinitionJsonSchema,
  RuntimeSubstrateDefinitionSchema,
  RuntimeSubstrateIntentDefinitionSchema,
  SUBSTRATE_DEFINITION_SCHEMA_URI,
  SubstrateDisclosureDefinitionSchema,
  SubstrateIdentityDefinitionSchema,
  SubstrateIntakeDefinitionSchema,
  SubstrateRelationDefinitionSchema,
  SubstrateWorkflowDefinitionSchema,
  SubstrateWorkflowTransitionDefinitionSchema,
  MEMORY_LAYERS,
  MEMORY_KINDS,
  TaskSubstrate,
  EpicSubstrate,
  FolderSubstrate,
  ArtifactSubstrate,
  MilestoneSubstrate,
  CronSubstrate,
  MemorySubstrate,
  type SubstrateDefinition,
  type SubstrateStructure,
  type SubstrateUI,
  type Task,
  type Epic,
  type Folder,
  type Artifact,
  type Milestone,
  type Cron,
  type Memory,
  // `<Type>Entity` aliases — the generic Entity narrowed per substrate (ADR 0106.2 §2)
  type TaskEntity,
  type EpicEntity,
  type FolderEntity,
  type ArtifactEntity,
  type MilestoneEntity,
  type CronEntity,
  type MemoryEntity,
  type MemoryLayerName,
  type MemoryKind,
  type RuntimeSubstrateDefinition,
  type RuntimeSubstrateIntentDefinition,
  type SubstrateDisclosureDefinition,
  type SubstrateRelationDefinition,
  type SubstrateIdentityDefinition,
  type SubstrateIntakeDefinition,
  type SubstrateWorkflowDefinition,
  type SubstrateWorkflowTransitionDefinition,
} from './substrates/index.js';

export { isValidCronExpression } from './cron-expression.js';

export {
  type OperationType,
  type StrReplaceOperation,
  type InsertOperation,
  type AppendOperation,
  type Operation,
  type EditOperation,
} from './write-operation.js';

export type {
  AnyEntity,
  RuntimeEntity,
  SubstrateType,
} from './runtime-entity.types.js';

export type {
  CompiledDisclosureRelation,
  CompiledSubstrateDisclosure,
  CompiledSubstrateGetDisclosure,
  CompiledSubstrateRecallDisclosure,
  CompiledSubstrateSearchDisclosure,
  CompiledSubstrateWakeupDisclosure,
} from './substrates/substrate-disclosure.types.js';

export type {
  CompiledFieldBinding,
  CompiledSubstrateIntent,
  CompiledSubstrateIntentOperation,
  CompiledSubstrateRelation,
  CompiledSubstrateTransition,
  JsonScalar,
  JsonValue,
  SubstrateRelationCardinality,
} from './substrates/substrate-intent.types.js';
